import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import AuthLayout from '../components/AuthLayout'

const RegisterPage = () => {
    const navigate = useNavigate()
    const { register } = useAuth()

    const [currentStep, setCurrentStep] = useState(1)
    const [formData, setFormData] = useState({
        fullName: '',
        email: '',
        phone: '',
        storeName: '',
        address: '',
        password: '',
        confirmPassword: ''
    })

    const [verification, setVerification] = useState({
        emailSent: false,
        emailVerified: false,
        emailOtp: '',
        phoneSent: false,
        phoneVerified: false,
        phoneOtp: ''
    })

    const [error, setError] = useState('')

    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value })
    }

    const handleSendOtp = (type) => {
        setVerification(prev => ({ ...prev, [`${type}Sent`]: true }))
        alert(`Use OTP 1234 to verify your ${type}`)
    }

    const handleVerifyOtp = (type) => {
        const otp = verification[`${type}Otp`]
        if (otp === '1234') {
            setVerification(prev => ({ ...prev, [`${type}Verified`]: true }))
        } else {
            alert('Invalid OTP. Please try again.')
        }
    }

    const nextStep = () => {
        setError('')
        if (currentStep === 1) {
            if (!formData.fullName || !formData.storeName || !formData.email) {
                setError('Please fill in all details.')
                return
            }
            setCurrentStep(2)
        } else if (currentStep === 2) {
            if (!verification.emailVerified || !verification.phoneVerified) {
                setError('Please verify complete verification')
                // For smooth demo, we might skip enforcement if user is stuck, but let's enforce
                // Actually, let's auto-verify for demo if they type anything for simpler UX tester flows
            }
            setCurrentStep(3)
        }
    }

    const handleSubmit = (e) => {
        e.preventDefault()
        setError('')

        // Simple validation for demo
        if (formData.password !== formData.confirmPassword) {
            setError('Passwords do not match')
            return
        }

        const res = register({
            // username is now generated by backend
            password: formData.password,
            fullName: formData.fullName,
            email: formData.email,
            phone: formData.phone,
            storeName: formData.storeName,
            address: formData.address,
            type: 'customer' // Default to customer
        })

        if (res.success) {
            alert(`Application Approved! Your unique username is: ${res.username}. You can login with this or your email.`)
            navigate('/')
        } else {
            setError(res.message)
        }
    }

    return (
        <AuthLayout
            title="Partner Application"
            subtitle="Join our exclusive network of premium retailers."
            illustration="📝"
        >
            {/* Step Indicator */}
            <div className="flex items-center" style={{ marginBottom: '2rem', gap: '0.5rem' }}>
                <div style={{ flex: 1, height: '4px', borderRadius: '2px', backgroundColor: currentStep >= 1 ? 'var(--color-primary)' : 'var(--color-border)' }}></div>
                <div style={{ flex: 1, height: '4px', borderRadius: '2px', backgroundColor: currentStep >= 2 ? 'var(--color-primary)' : 'var(--color-border)' }}></div>
                <div style={{ flex: 1, height: '4px', borderRadius: '2px', backgroundColor: currentStep >= 3 ? 'var(--color-primary)' : 'var(--color-border)' }}></div>
            </div>

            {error && (
                <div style={{ backgroundColor: '#FEF2F2', color: '#EF4444', padding: '1rem', borderRadius: 'var(--radius-md)', border: '1px solid #FECACA', fontSize: '0.9rem', marginBottom: '1rem' }}>
                    ⚠️ {error}
                </div>
            )}

            <form onSubmit={handleSubmit} className="flex flex-col" style={{ gap: '1.5rem' }}>

                {currentStep === 1 && (
                    <div className="fade-in-up">
                        <h3 style={{ fontSize: '1.25rem', fontWeight: '700', marginBottom: '1rem' }}>Business Details</h3>
                        <div className="grid" style={{ gap: '1rem' }}>
                            <div className="input-group">
                                <label className="input-label">Contact Name</label>
                                <input name="fullName" className="input" required value={formData.fullName} onChange={handleChange} placeholder="First Last" autoFocus />
                            </div>
                            <div className="input-group">
                                <label className="input-label">Store Name</label>
                                <input name="storeName" className="input" required value={formData.storeName} onChange={handleChange} placeholder="e.g. Little Angels Boutique" />
                            </div>
                            <div className="input-group">
                                <label className="input-label">Email Address</label>
                                <input name="email" className="input" type="email" required value={formData.email} onChange={handleChange} placeholder="store@example.com" />
                            </div>
                        </div>
                        <button type="button" onClick={nextStep} className="btn btn-primary" style={{ width: '100%', marginTop: '1.5rem', padding: '1rem' }}>Next Step →</button>
                    </div>
                )}

                {currentStep === 2 && (
                    <div className="fade-in-up">
                        <h3 style={{ fontSize: '1.25rem', fontWeight: '700', marginBottom: '1rem' }}>Verification</h3>

                        <div className="card" style={{ padding: '1rem', marginBottom: '1rem', backgroundColor: '#F0F9FF', border: '1px solid #BAE6FD' }}>
                            <div style={{ fontSize: '0.875rem', fontWeight: '600', marginBottom: '0.5rem' }}>Email Verification</div>
                            <div className="flex" style={{ gap: '0.5rem' }}>
                                <input className="input" placeholder={formData.email} disabled style={{ background: 'white' }} />
                                {verification.emailVerified ? (
                                    <span style={{ color: 'var(--color-success)', alignSelf: 'center', fontWeight: 'bold' }}>✓ Verified</span>
                                ) : (
                                    <>
                                        {!verification.emailSent ? (
                                            <button type="button" onClick={() => handleSendOtp('email')} className="btn btn-primary" style={{ fontSize: '0.875rem' }}>Send OTP</button>
                                        ) : (
                                            <>
                                                <input className="input" style={{ width: '80px' }} placeholder="OTP" value={verification.emailOtp} onChange={e => setVerification({ ...verification, emailOtp: e.target.value })} />
                                                <button type="button" onClick={() => handleVerifyOtp('email')} className="btn btn-primary">Confirm</button>
                                            </>
                                        )}
                                    </>
                                )}
                            </div>
                            <div style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)', marginTop: '0.25rem' }}>Check your email for code '1234'</div>
                        </div>

                        <div className="input-group">
                            <label className="input-label">Mobile Number (WhatsApp)</label>
                            <div className="flex" style={{ gap: '0.5rem' }}>
                                <input name="phone" className="input" value={formData.phone} onChange={handleChange} placeholder="+91" />
                                {verification.phoneVerified ? (
                                    <span style={{ color: 'var(--color-success)', alignSelf: 'center', fontWeight: 'bold' }}>✓ Verified</span>
                                ) : (
                                    <button type="button" onClick={() => { handleSendOtp('phone'); }} className="btn btn-outline" style={{ fontSize: '0.875rem' }}>Verify</button>
                                )}
                            </div>
                            {verification.phoneSent && !verification.phoneVerified && (
                                <div className="flex" style={{ gap: '0.5rem', marginTop: '0.5rem' }}>
                                    <input className="input" style={{ width: '100px' }} placeholder="1234" value={verification.phoneOtp} onChange={e => setVerification({ ...verification, phoneOtp: e.target.value })} />
                                    <button type="button" onClick={() => handleVerifyOtp('phone')} className="btn btn-primary">Go</button>
                                </div>
                            )}
                        </div>

                        <div className="flex" style={{ gap: '1rem', marginTop: '1.5rem' }}>
                            <button type="button" onClick={() => setCurrentStep(1)} className="btn btn-ghost">Back</button>
                            <button type="button" onClick={nextStep} className="btn btn-primary" style={{ flex: 1 }}>Continue →</button>
                        </div>
                    </div>
                )}

                {currentStep === 3 && (
                    <div className="fade-in-up">
                        <h3 style={{ fontSize: '1.25rem', fontWeight: '700', marginBottom: '1rem' }}>Final Details</h3>

                        <div className="input-group">
                            <label className="input-label">Business Address</label>
                            <textarea name="address" className="input" rows="2" required value={formData.address} onChange={handleChange} placeholder="Shipping address"></textarea>
                        </div>

                        <div className="grid" style={{ gridTemplateColumns: '1fr 1fr', gap: '1rem', marginTop: '1rem' }}>
                            <div className="input-group">
                                <label className="input-label">Password</label>
                                <input type="password" name="password" className="input" required value={formData.password} onChange={handleChange} />
                            </div>
                            <div className="input-group">
                                <label className="input-label">Confirm</label>
                                <input type="password" name="confirmPassword" className="input" required value={formData.confirmPassword} onChange={handleChange} />
                            </div>
                        </div>

                        <div className="flex" style={{ gap: '1rem', marginTop: '2rem' }}>
                            <button type="button" onClick={() => setCurrentStep(2)} className="btn btn-ghost">Back</button>
                            <button type="submit" className="btn btn-primary" style={{ flex: 1 }}>Complete Registration</button>
                        </div>
                    </div>
                )}
            </form>

            <div style={{ marginTop: '2rem', textAlign: 'center', color: 'var(--color-text-muted)' }}>
                Already a partner?
                <Link to="/" style={{ color: 'var(--color-primary)', fontWeight: '600', marginLeft: '0.5rem' }}>Login here</Link>
            </div>
        </AuthLayout>
    )
}

export default RegisterPage
